"""Structural ports for durable execution infrastructure."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Mapping, Protocol, runtime_checkable

from .durable_execution import (
    DurableTimerRecord, JobRecord, JobScanCursor, LeaseRecord, LeaseScanCursor,
    TimerScanCursor,
)
from .ids import EntityId
from .versions import AggregateVersion


@runtime_checkable
class JobRepositoryPort(Protocol):
    def create(self, record: JobRecord) -> None: ...
    def get(self, job_id: EntityId) -> JobRecord | None: ...
    def update(self, record: JobRecord, expected: AggregateVersion) -> None: ...
    def list_by_run(self, run_id: EntityId) -> tuple[JobRecord, ...]: ...
    def list_claimable(self, now: datetime, *, after: JobScanCursor | None = None, limit: int = 100) -> tuple[JobRecord, ...]: ...


@runtime_checkable
class LeaseRepositoryPort(Protocol):
    def create(self, record: LeaseRecord) -> None: ...
    def get(self, lease_id: EntityId) -> LeaseRecord | None: ...
    def get_active_for_job(self, job_id: EntityId) -> LeaseRecord | None: ...
    def list_by_job(self, job_id: EntityId) -> tuple[LeaseRecord, ...]: ...
    def update(self, record: LeaseRecord, expected: AggregateVersion) -> None: ...
    def renew(self, lease_id: EntityId, *, token_hash: str, fencing_token: int, expected_revision: int, expires_at: datetime) -> LeaseRecord: ...
    def list_expired(self, now: datetime, *, after: LeaseScanCursor | None = None, limit: int = 100) -> tuple[LeaseRecord, ...]: ...


@runtime_checkable
class TimerRepositoryPort(Protocol):
    def create(self, record: DurableTimerRecord) -> None: ...
    def get(self, timer_id: EntityId) -> DurableTimerRecord | None: ...
    def get_by_dedupe(self, run_id: EntityId, purpose: str, dedupe_key: str) -> DurableTimerRecord | None: ...
    def update(self, record: DurableTimerRecord, expected: AggregateVersion) -> None: ...
    def list_due(self, now: datetime, *, after: TimerScanCursor | None = None, limit: int = 100) -> tuple[DurableTimerRecord, ...]: ...
    def list_expired_leases(self, now: datetime, *, limit: int = 100) -> tuple[DurableTimerRecord, ...]: ...
    def list_by_run(self, run_id: EntityId) -> tuple[DurableTimerRecord, ...]: ...


@runtime_checkable
class ExecutorPort(Protocol):
    def execute(self, request: Mapping[str, Any], cancellation_token: Any) -> Any: ...


@runtime_checkable
class DurableExecutionMetricsPort(Protocol):
    def increment(self, name: str, value: int = 1, **labels: str) -> None: ...
    def observe(self, name: str, value: float, **labels: str) -> None: ...
